<a href="https://colab.research.google.com/github/ksejull/labs/blob/main/%D0%9B%D0%A04_%D0%9B%D1%83%D1%87%D0%B0%D0%BD%D1%96%D0%BD%D0%BE%D0%B2%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Лучанінова Ксенія, Варіант 11, Група 2-8

#Лабораторна робота №4

###1.

1.1)

In [2]:
import numpy as np

# Задання матриці A і B
A = np.array([[1, 2], [4, -1]])
B = np.array([[2, -3], [-4, 1]])

# Обчислення матриці C = AB - BA
C = np.dot(A, B) - np.dot(B, A)

# Виводення результату
print("Матриця C = AB - BA:")
print(C)


Матриця C = AB - BA:
[[ 4 -8]
 [12 -4]]


2.1)

In [6]:
import numpy as np

# Задання матриці
matrix = np.array([[-1, 2], [0, 1]])

# Піднесення матриці до степеня 2
matrix_squared = np.linalg.matrix_power(matrix, 2)

# Виведення результату
print("Матриця, піднесена до степеня 2:")
print(matrix_squared)


Матриця, піднесена до степеня 2:
[[1 0]
 [0 1]]


3.1)

In [11]:
import numpy as np

# Задання матриць
a = np.array([[3, 5], [6, -1]])
b = np.array([[2, 1], [-3, 2]])

# Обчислення добутку матриць A і B
product = np.dot(a, b)

# Виведення результату
print("Добуток матриць A * B:")
print(product)


Добуток матриць A * B:
[[-9 13]
 [15  4]]


4.1)

In [12]:
import numpy as np

# Задання матриці
matrix = np.array([[2, 3, 4], [1, 0, 6], [7, 8, 9]])

# Обчислення визначника
determinant = np.linalg.det(matrix)

# Виведення результату
print(f"Визначник матриці: {determinant:.2f}")


Визначник матриці: 35.00


5.2)

In [13]:
import numpy as np

# Задання матриці
matrix = np.array([[2, 3, 4, 1],
                   [1, 2, 3, 4],
                   [3, 4, 1, 2],
                   [4, 1, 2, 3]])

# Обчислення визначника
determinant = np.linalg.det(matrix)

# Виведення результату
print(f"Визначник матриці: {determinant:.2f}")

Визначник матриці: -160.00


6.1)

In [2]:
import numpy as np

# Задання матриці
matrix = np.array([[1, 2, -3],
                   [0, 1, 2],
                   [0, 0, 1]])

# Обчислення оберненої матриці
inverse_matrix = np.linalg.inv(matrix)

# Виведення результату
print("Обернена матриця:")
print(inverse_matrix)

Обернена матриця:
[[ 1. -2.  7.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]]


7.1)

In [3]:
import numpy as np

# Задання матриці
matrix = np.array([[1, 2, 3, 4],
                   [3, -1, 2, 5],
                   [1, 2, 3, 4],
                   [1, 3, 4, 5]])

# Обчислення рангу матриці
rank = np.linalg.matrix_rank(matrix)

# Виведення результату
print(f"Ранг матриці: {rank}")

Ранг матриці: 2


8.1)

In [4]:
import numpy as np

# Матричний метод
def matrix_method(coefficients, constants):
    inverse_matrix = np.linalg.inv(coefficients)
    return np.dot(inverse_matrix, constants)

# Метод Крамера
def cramer_method(coefficients, constants):
    det_coefficients = np.linalg.det(coefficients)
    if det_coefficients == 0:
        raise ValueError("Детермінант матриці коефіцієнтів дорівнює нулю. Система може не мати унікального розв'язку.")

    solutions = []
    for i in range(len(coefficients)):
        modified_coefficients = np.copy(coefficients)
        modified_coefficients[:, i] = constants
        solutions.append(np.linalg.det(modified_coefficients) / det_coefficients)
    return solutions

# Метод Гауса
def gauss_method(a, b):
    a = np.array(a, dtype=float)
    b = np.array(b, dtype=float)
    n = len(b)

    # Прямий хід
    for k in range(n):
        for i in range(k + 1, n):
            if a[i, k] != 0:
                lam = a[i, k] / a[k, k]
                a[i, k:] -= lam * a[k, k:]
                b[i] -= lam * b[k]

    # Зворотний хід
    x = np.zeros(n)
    for k in range(n - 1, -1, -1):
        x[k] = (b[k] - np.dot(a[k, k+1:], x[k+1:])) / a[k, k]

    return x

def main():
    # Матриця коефіцієнтів і вектор констант
    a = np.array([[14, 4, 6],
                  [5, -3, 2],
                  [10, -11, 5]])
    b = np.array([30, 15, 36])

    # Матричний метод
    X_matrix = matrix_method(a, b)
    print("Матричний метод:", X_matrix)

    # Метод Крамера
    X_cramer = cramer_method(a, b)
    print("Метод Крамера:", X_cramer)

    # Метод Гауса
    X_gauss = gauss_method(a, b)
    print("Метод Гауса:", X_gauss)

    # Перевірка за допомогою np.linalg.solve
    X_solve = np.linalg.solve(a, b)
    print("Перевірка linalg solve():", X_solve)

if __name__ == "__main__":
    main()

Матричний метод: [ 2. -1.  1.]
Метод Крамера: [2.0000000000000018, -1.0, 0.9999999999999972]
Метод Гауса: [ 2. -1.  1.]
Перевірка linalg solve(): [ 2. -1.  1.]


###2.

1.


In [1]:
import numpy as np

# Функція для створення випадкової матриці і знаходження найменшого стовпчикового елемента
def find_min_element_of_max_sum_column(n, m):
    # Створення випадкової матриці
    a = np.random.randint(-10, 10, size=(n, m))
    print("Матриця A:")
    print(a)

    # Обчислення суми абсолютних значень для кожного стовпця
    abs_column_sums = np.sum(np.abs(a), axis=0)

    # Знаходження індексу стовпця з максимальною сумою
    max_sum_column_index = np.argmax(abs_column_sums)

    # Витягування стовпця з максимальними сумами
    max_sum_column = a[:, max_sum_column_index]

    # Знаходження найменшого елемента у цьому стовпці
    min_element = np.min(max_sum_column)

    return min_element

def main():
    # Розміри матриці
    n = 4  # Кількість рядків
    m = 5  # Кількість стовпців

    # Виклик функції і друк результату
    min_element = find_min_element_of_max_sum_column(n, m)
    print("Найменший стовпчиковий елемент, для якого сума абсолютних значень максимальна:", min_element)

if __name__ == "__main__":
    main()

Матриця A:
[[ -9  -4  -7   7   8]
 [  9   7  -3  -6  -4]
 [-10 -10  -4  -2   1]
 [ -9   0  -9  -7   2]]
Найменший стовпчиковий елемент, для якого сума абсолютних значень максимальна: -10
